# Generated by Django 5.2.6 on 2025-10-05 22:53

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("r_name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=20)),
                (
                    "cuisine",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "rating_count_str",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "avg_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("lic_no", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
