# Generated by Django 5.2.6 on 2025-10-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_restaurant_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="r_image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
