# Generated by Django 5.2.6 on 2025-10-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_restaurant_r_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="avg_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
