# Generated by Django 5.2.6 on 2025-10-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_alter_restaurant_avg_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="rating_count_int",
            field=models.IntegerField(default=0),
        ),
    ]
