# Generated by Django 5.2.7 on 2025-11-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_cart_cartitems_order_orderitems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="restaurant_id",
            new_name="restaurant",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="restaurant_id",
            new_name="restaurant",
        ),
    ]
