from .cart_manage_get_docs import cart_get_schema
from .cart_manage_delete_docs import cart_delete_schema
from .cart_item_post_docs import add_remove_cart_item_schema
from .cart_item_delete_docs import delete_cart_item_schema
from .cities_available_docs import cities_get_schema
from .restaurant_filter_docs import restaurants_filter_schema
from .open_restaurant_docs import one_restaurant_schema